"""Initial schema with Decimal

Revision ID: 548f865fec9b
Revises: 
Create Date: 2026-08-28 17:44:55.928199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548f865fec9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('execution_record', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.add_column('recovery_cases', sa.Column('reference_id', sa.String(), nullable=True))
    op.add_column('recovery_cases', sa.Column('risk_assessment', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('diagnosis', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('prediction', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('recommendation', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('policy_decision', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('execution_record', sa.JSON(), nullable=True))
    op.add_column('recovery_cases', sa.Column('outcome', sa.JSON(), nullable=True))
    op.alter_column('recovery_cases', 'amount_at_risk',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.create_index(op.f('ix_recovery_cases_reference_id'), 'recovery_cases', ['reference_id'], unique=False)
    op.add_column('revenue_events', sa.Column('reference_id', sa.String(), nullable=True))
    op.alter_column('revenue_events', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.drop_index(op.f('ix_revenue_events_external_event_id'), table_name='revenue_events')
    op.create_index(op.f('ix_revenue_events_external_event_id'), 'revenue_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_reference_id'), 'revenue_events', ['reference_id'], unique=False)
    op.create_unique_constraint('uq_external_event_sys_id', 'revenue_events', ['external_system', 'external_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_external_event_sys_id', 'revenue_events', type_='unique')
    op.drop_index(op.f('ix_revenue_events_reference_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_external_event_id'), table_name='revenue_events')
    op.create_index(op.f('ix_revenue_events_external_event_id'), 'revenue_events', ['external_event_id'], unique=1)
    op.alter_column('revenue_events', 'amount',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('revenue_events', 'reference_id')
    op.drop_index(op.f('ix_recovery_cases_reference_id'), table_name='recovery_cases')
    op.alter_column('recovery_cases', 'amount_at_risk',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('recovery_cases', 'outcome')
    op.drop_column('recovery_cases', 'execution_record')
    op.drop_column('recovery_cases', 'policy_decision')
    op.drop_column('recovery_cases', 'recommendation')
    op.drop_column('recovery_cases', 'prediction')
    op.drop_column('recovery_cases', 'diagnosis')
    op.drop_column('recovery_cases', 'risk_assessment')
    op.drop_column('recovery_cases', 'reference_id')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
