"""initial schema

Revision ID: 65f466d3a831
Revises: 
Create Date: 2026-08-31 00:00:22.846237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f466d3a831'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'PROFILING', 'MAPPING_REVIEW', 'READY_FOR_ANALYSIS', 'ANALYZING', 'COMPLETED', 'ML_READY', 'TRAINING', 'TRAINED', 'FAILED', name='datasetstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('duplicate_row_count', sa.Integer(), nullable=True),
    sa.Column('total_missing_values', sa.Integer(), nullable=True),
    sa.Column('columns_profile', sa.JSON(), nullable=True),
    sa.Column('data_quality_report', sa.JSON(), nullable=True),
    sa.Column('temporal_analysis', sa.JSON(), nullable=True),
    sa.Column('training_suitability', sa.JSON(), nullable=True),
    sa.Column('recoverchain_signals', sa.JSON(), nullable=True),
    sa.Column('target_detection', sa.JSON(), nullable=True),
    sa.Column('leakage_detection', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_datasets_dataset_id'), 'datasets', ['dataset_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('execution_record', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_table('recovery_cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('risk_category', sa.Enum('FAILED_PAYMENT', 'CHECKOUT_ABANDONMENT', 'FAILED_SUBSCRIPTION', 'OVERDUE_INVOICE', 'BROKEN_PROMISE', name='riskcategory'), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('amount_at_risk', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('expected_recoverable_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('current_state', sa.Enum('DETECTED', 'OPEN', 'DIAGNOSING', 'RECOMMENDING', 'POLICY_EVALUATED', 'ASSESSED', 'ACTION_PROPOSED', 'POLICY_REVIEW', 'APPROVED', 'DENIED', 'WAITING', 'ESCALATED', 'EXECUTION_PREPARING', 'EXECUTING', 'VERIFYING', 'FULLY_RECOVERED', 'PARTIALLY_RECOVERED', 'CLOSED_NOT_RECOVERED', 'PENDING_VERIFICATION', 'STOPPED', name='casestate'), nullable=False),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('prediction', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('policy_decision', sa.JSON(), nullable=True),
    sa.Column('execution_record', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_recovery_cases_case_id'), 'recovery_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_customer_id'), 'recovery_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_reference_id'), 'recovery_cases', ['reference_id'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_case_id'), 'audit_records', ['case_id'], unique=False)
    op.create_table('revenue_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('external_system', sa.String(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('risk_category', sa.Enum('FAILED_PAYMENT', 'CHECKOUT_ABANDONMENT', 'FAILED_SUBSCRIPTION', 'OVERDUE_INVOICE', 'BROKEN_PROMISE', name='riskcategory'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.case_id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('external_system', 'external_event_id', name='uq_external_event_sys_id')
    )
    op.create_index(op.f('ix_revenue_events_event_id'), 'revenue_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_external_event_id'), 'revenue_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_reference_id'), 'revenue_events', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_events_reference_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_external_event_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_event_id'), table_name='revenue_events')
    op.drop_table('revenue_events')
    op.drop_index(op.f('ix_audit_records_case_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_recovery_cases_reference_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_customer_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_case_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_datasets_dataset_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
