"""execution_attempts ledger

Revision ID: 6aaf57d8d4b5
Revises: 65f466d3a831
Create Date: 2026-08-31 00:08:37.355182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaf57d8d4b5'
down_revision: Union[str, Sequence[str], None] = '65f466d3a831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_attempts_case_id'), 'execution_attempts', ['case_id'], unique=False)
    op.create_index(op.f('ix_execution_attempts_created_at'), 'execution_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_attempts_idempotency_key'), 'execution_attempts', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_attempts_idempotency_key'), table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_created_at'), table_name='execution_attempts')
    op.drop_index(op.f('ix_execution_attempts_case_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    # ### end Alembic commands ###
